export type TTrainingType =
  | 'learning-from-image-english'
  | 'beginner-from-english'
  | 'beginner-from-image-russian'
  | 'beginner-from-image-only'
  | 'intermediate-from-image-russian'
  | 'intermediate-from-definition'
  | 'advanced-from-russian'
  | 'advanced-from-definition'
  | 'advanced-from-english'
